package main

import (
	"fmt"
	"io"
)

func printUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli version")
	fmt.Fprintln(w, "  synchub-cli version --json")
	fmt.Fprintln(w, "  synchub-cli server status --server http://localhost:8765")
	fmt.Fprintln(w, "  synchub-cli server status --server http://localhost:8765 --json")
	fmt.Fprintln(w, "  synchub-cli server wait --server http://localhost:8765 --timeout 30s")
	fmt.Fprintln(w, "  synchub-cli server wait --server http://localhost:8765 --timeout 30s --json")
	fmt.Fprintln(w, "  synchub-cli server metrics --server http://localhost:8765")
	fmt.Fprintln(w, "  synchub-cli server metrics --server http://localhost:8765 --json")
	fmt.Fprintln(w, "  synchub-cli server openapi --server http://localhost:8765")
	fmt.Fprintln(w, "  synchub-cli server openapi --server http://localhost:8765 --output ./openapi.yaml")
	fmt.Fprintln(w, "  synchub-cli server openapi --server http://localhost:8765 --output ./openapi.yaml --json")
	fmt.Fprintln(w, "  synchub-cli register --server http://localhost:8765 --email user@example.com --password password")
	fmt.Fprintln(w, "  synchub-cli register --server http://localhost:8765 --email user@example.com --password password --json")
	fmt.Fprintln(w, "  synchub-cli login --server http://localhost:8765 --email user@example.com --password password")
	fmt.Fprintln(w, "  synchub-cli login --server http://localhost:8765 --email user@example.com --password password --json")
	fmt.Fprintln(w, "  synchub-cli logout")
	fmt.Fprintln(w, "  synchub-cli logout --json")
	fmt.Fprintln(w, "  synchub-cli workspace init --path . --remote-path /workspace")
	fmt.Fprintln(w, "  synchub-cli workspace init --path . --remote-path /workspace --json")
	fmt.Fprintln(w, "  synchub-cli workspace init --remote-root /workspace C:\\work\\notes D:\\work\\code")
	fmt.Fprintln(w, "  synchub-cli workspace list")
	fmt.Fprintln(w, "  synchub-cli workspace list --json")
	fmt.Fprintln(w, "  synchub-cli manifest scan --path .")
	fmt.Fprintln(w, "  synchub-cli manifest scan --path . --json")
	fmt.Fprintln(w, "  synchub-cli manifest scan --path . --dry-run")
	fmt.Fprintln(w, "  synchub-cli manifest ignores --path .")
	fmt.Fprintln(w, "  synchub-cli manifest ignores --path . --json")
	fmt.Fprintln(w, "  synchub-cli file list --path .")
	fmt.Fprintln(w, "  synchub-cli file list --path . --json")
	fmt.Fprintln(w, "  synchub-cli file download --path . --remote-path /workspace/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file download --path . --remote-path /workspace/readme.txt --json")
	fmt.Fprintln(w, "  synchub-cli file delete --path . --remote-path /workspace/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file delete --path . --remote-path /workspace/readme.txt --json")
	fmt.Fprintln(w, "  synchub-cli file move --path . --remote-path /workspace/readme.txt --to /workspace/docs/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file move --path . --remote-path /workspace/readme.txt --to /workspace/docs/readme.txt --json")
	fmt.Fprintln(w, "  synchub-cli file mkdir --path . --remote-path /workspace/docs")
	fmt.Fprintln(w, "  synchub-cli file mkdir --path . --remote-path /workspace/docs --json")
	fmt.Fprintln(w, "  synchub-cli file versions --path . --remote-path /workspace/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file versions --path . --remote-path /workspace/readme.txt --json")
	fmt.Fprintln(w, "  synchub-cli file restore --path . --remote-path /workspace/readme.txt --version 1")
	fmt.Fprintln(w, "  synchub-cli file restore --path . --remote-path /workspace/readme.txt --version 1 --json")
	fmt.Fprintln(w, "  synchub-cli file pin --path . --remote-path /workspace/readme.txt --version 1")
	fmt.Fprintln(w, "  synchub-cli file pin --path . --remote-path /workspace/readme.txt --version 1 --json")
	fmt.Fprintln(w, "  synchub-cli upload status --path . --id upl_1")
	fmt.Fprintln(w, "  synchub-cli upload status --path . --id upl_1 --json")
	fmt.Fprintln(w, "  synchub-cli sync once --path .")
	fmt.Fprintln(w, "  synchub-cli sync once --path . --dry-run")
	fmt.Fprintln(w, "  synchub-cli sync once --path . --dry-run --json")
	fmt.Fprintln(w, "  synchub-cli sync status --path .")
	fmt.Fprintln(w, "  synchub-cli sync status --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync status --path . --show-remote")
	fmt.Fprintln(w, "  synchub-cli sync status --path . --show-conflicts")
	fmt.Fprintln(w, "  synchub-cli sync doctor --path .")
	fmt.Fprintln(w, "  synchub-cli sync doctor --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync push --path .")
	fmt.Fprintln(w, "  synchub-cli sync push --path . --dry-run")
	fmt.Fprintln(w, "  synchub-cli sync push --path . --dry-run --json")
	fmt.Fprintln(w, "  synchub-cli sync push --path . --device-name laptop --platform windows")
	fmt.Fprintln(w, "  synchub-cli sync pull --path .")
	fmt.Fprintln(w, "  synchub-cli sync pull --path . --dry-run")
	fmt.Fprintln(w, "  synchub-cli sync pull --path . --dry-run --json")
	fmt.Fprintln(w, "  synchub-cli sync pull --path . --reset-cursor")
	fmt.Fprintln(w, "  synchub-cli sync daemon")
	fmt.Fprintln(w, "  synchub-cli sync daemon --foreground")
	fmt.Fprintln(w, "  synchub-cli sync daemon --status")
	fmt.Fprintln(w, "  synchub-cli sync daemon --pause")
	fmt.Fprintln(w, "  synchub-cli sync daemon --resume")
	fmt.Fprintln(w, "  synchub-cli sync trash --path .")
	fmt.Fprintln(w, "  synchub-cli sync trash --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync trash restore --path . --batch 20260702T010000.000000000Z --entry docs/")
	fmt.Fprintln(w, "  synchub-cli sync trash restore --path . --batch 20260702T010000.000000000Z --entry docs/ --json")
	fmt.Fprintln(w, "  synchub-cli sync devices --path .")
	fmt.Fprintln(w, "  synchub-cli sync devices --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync conflicts --path .")
	fmt.Fprintln(w, "  synchub-cli sync conflicts --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync conflicts resolve --path . --id conf_1 --resolution keep_both")
	fmt.Fprintln(w, "  synchub-cli sync conflicts resolve --path . --id conf_1 --resolution keep_both --json")
}

func printWorkspaceUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli workspace init --path . --remote-path /workspace")
	fmt.Fprintln(w, "  synchub-cli workspace init --path . --remote-path /workspace --json")
	fmt.Fprintln(w, "  synchub-cli workspace init --remote-root /workspace C:\\work\\notes D:\\work\\code")
	fmt.Fprintln(w, "  synchub-cli workspace list")
	fmt.Fprintln(w, "  synchub-cli workspace list --json")
}

func printServerUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli server status --server http://localhost:8765")
	fmt.Fprintln(w, "  synchub-cli server status --server http://localhost:8765 --json")
	fmt.Fprintln(w, "  synchub-cli server wait --server http://localhost:8765 --timeout 30s")
	fmt.Fprintln(w, "  synchub-cli server wait --server http://localhost:8765 --timeout 30s --json")
	fmt.Fprintln(w, "  synchub-cli server metrics --server http://localhost:8765")
	fmt.Fprintln(w, "  synchub-cli server metrics --server http://localhost:8765 --json")
	fmt.Fprintln(w, "  synchub-cli server openapi --server http://localhost:8765")
	fmt.Fprintln(w, "  synchub-cli server openapi --server http://localhost:8765 --output ./openapi.yaml")
	fmt.Fprintln(w, "  synchub-cli server openapi --server http://localhost:8765 --output ./openapi.yaml --json")
}

func printManifestUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli manifest scan --path .")
	fmt.Fprintln(w, "  synchub-cli manifest scan --path . --json")
	fmt.Fprintln(w, "  synchub-cli manifest scan --path . --dry-run")
	fmt.Fprintln(w, "  synchub-cli manifest ignores --path .")
	fmt.Fprintln(w, "  synchub-cli manifest ignores --path . --json")
}

func printFileUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli file list --path .")
	fmt.Fprintln(w, "  synchub-cli file list --path . --json")
	fmt.Fprintln(w, "  synchub-cli file list --path . --remote-path /workspace/docs")
	fmt.Fprintln(w, "  synchub-cli file list --path . --parent-id dir_1")
	fmt.Fprintln(w, "  synchub-cli file list --path . --parent-id dir_1 --cursor file_1")
	fmt.Fprintln(w, "  synchub-cli file download --path . --remote-path /workspace/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file download --path . --file-id file_1 --output ./readme.txt")
	fmt.Fprintln(w, "  synchub-cli file download --path . --file-id file_1 --output ./readme.txt --json")
	fmt.Fprintln(w, "  synchub-cli file download --path . --file-id file_1 --range bytes=0-1023 --if-none-match '\"etag\"'")
	fmt.Fprintln(w, "  synchub-cli file delete --path . --remote-path /workspace/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file delete --path . --file-id file_1")
	fmt.Fprintln(w, "  synchub-cli file delete --path . --file-id file_1 --json")
	fmt.Fprintln(w, "  synchub-cli file move --path . --remote-path /workspace/readme.txt --to /workspace/docs/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file move --path . --file-id file_1 --to /workspace/docs/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file move --path . --file-id file_1 --to /workspace/docs/readme.txt --json")
	fmt.Fprintln(w, "  synchub-cli file mkdir --path . --remote-path /workspace/docs")
	fmt.Fprintln(w, "  synchub-cli file mkdir --path . --remote-path /workspace/docs --json")
	fmt.Fprintln(w, "  synchub-cli file versions --path . --remote-path /workspace/readme.txt")
	fmt.Fprintln(w, "  synchub-cli file versions --path . --remote-path /workspace/readme.txt --json")
	fmt.Fprintln(w, "  synchub-cli file versions --path . --file-id file_1")
	fmt.Fprintln(w, "  synchub-cli file restore --path . --remote-path /workspace/readme.txt --version 1")
	fmt.Fprintln(w, "  synchub-cli file restore --path . --file-id file_1 --version 1")
	fmt.Fprintln(w, "  synchub-cli file restore --path . --file-id file_1 --version 1 --json")
	fmt.Fprintln(w, "  synchub-cli file pin --path . --remote-path /workspace/readme.txt --version 1")
	fmt.Fprintln(w, "  synchub-cli file pin --path . --remote-path /workspace/readme.txt --version 1 --json")
	fmt.Fprintln(w, "  synchub-cli file unpin --path . --file-id file_1 --version 1")
	fmt.Fprintln(w, "  synchub-cli file unpin --path . --file-id file_1 --version 1 --json")
}

func printUploadUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli upload status --path . --id upl_1")
	fmt.Fprintln(w, "  synchub-cli upload status --path . --id upl_1 --json")
}

func printSyncUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli sync once --path .")
	fmt.Fprintln(w, "  synchub-cli sync once --path . --dry-run")
	fmt.Fprintln(w, "  synchub-cli sync once --path . --dry-run --json")
	fmt.Fprintln(w, "  synchub-cli sync status --path .")
	fmt.Fprintln(w, "  synchub-cli sync status --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync status --path . --show-remote")
	fmt.Fprintln(w, "  synchub-cli sync status --path . --show-conflicts")
	fmt.Fprintln(w, "  synchub-cli sync doctor --path .")
	fmt.Fprintln(w, "  synchub-cli sync doctor --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync push --path .")
	fmt.Fprintln(w, "  synchub-cli sync push --path . --dry-run")
	fmt.Fprintln(w, "  synchub-cli sync push --path . --dry-run --json")
	fmt.Fprintln(w, "  synchub-cli sync push --path . --device-name laptop --platform windows")
	fmt.Fprintln(w, "  synchub-cli sync pull --path .")
	fmt.Fprintln(w, "  synchub-cli sync pull --path . --dry-run")
	fmt.Fprintln(w, "  synchub-cli sync pull --path . --dry-run --json")
	fmt.Fprintln(w, "  synchub-cli sync pull --path . --reset-cursor")
	fmt.Fprintln(w, "  synchub-cli sync daemon")
	fmt.Fprintln(w, "  synchub-cli sync daemon --foreground")
	fmt.Fprintln(w, "  synchub-cli sync daemon --status")
	fmt.Fprintln(w, "  synchub-cli sync daemon --pause")
	fmt.Fprintln(w, "  synchub-cli sync daemon --resume")
	fmt.Fprintln(w, "  synchub-cli sync trash --path .")
	fmt.Fprintln(w, "  synchub-cli sync trash --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync trash restore --path . --batch 20260702T010000.000000000Z --entry docs/")
	fmt.Fprintln(w, "  synchub-cli sync trash restore --path . --batch 20260702T010000.000000000Z --entry docs/ --json")
	fmt.Fprintln(w, "  synchub-cli sync devices --path .")
	fmt.Fprintln(w, "  synchub-cli sync devices --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync conflicts --path .")
	fmt.Fprintln(w, "  synchub-cli sync conflicts --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync conflicts resolve --path . --id conf_1 --resolution keep_both")
	fmt.Fprintln(w, "  synchub-cli sync conflicts resolve --path . --id conf_1 --resolution keep_both --json")
}

func printSyncConflictsUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli sync conflicts --path .")
	fmt.Fprintln(w, "  synchub-cli sync conflicts --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync conflicts resolve --path . --id conf_1 --resolution keep_both")
	fmt.Fprintln(w, "  synchub-cli sync conflicts resolve --path . --id conf_1 --resolution keep_both --json")
}

func printSyncTrashUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  synchub-cli sync trash --path .")
	fmt.Fprintln(w, "  synchub-cli sync trash --path . --json")
	fmt.Fprintln(w, "  synchub-cli sync trash restore --path . --batch 20260702T010000.000000000Z --entry docs/")
	fmt.Fprintln(w, "  synchub-cli sync trash restore --path . --batch 20260702T010000.000000000Z --entry docs/ --json")
}
